#!/usr/bin/env sh
# Creates the MySQL test database centralvet_test from the files on disk
# (T-05, rodada 3). Run ONCE, from /var/www/html/centralvet, only with a
# specific SQL approval from the user (see docs/runbooks/tests.md
# "Banco MySQL de teste"). It never touches the application database.
#
#   step 1 (root of the mysql container): CREATE DATABASE + GRANTs on
#          centralvet_test.* to MIGRATION_DB_USER and MYSQL_USER;
#   step 2 (migration user): Adianti base, missing Adianti FKs and the
#          migrations 0001..0011, in order, stopping at the first error.
#
# The Adianti base comes from var/sql-bootstrap/ (generated by
# scripts/prepare-adianti-bootstrap.sh: sanitized seeds and MySQL-valid
# comments), never from src/app/database/*.sql directly: those use
# SQLite-style `---` headings, which MySQL rejects (ERROR 1064).
#
# Before any docker call, a preflight checks that every file exists and that
# none starts a line with `---`. `--check` runs only that preflight (no
# docker, no SQL) and exits. TEST_DB_BOOTSTRAP_DIR overrides the bootstrap
# directory (used by provision-check.test.sh).
#
# Refuses (exit 1) when centralvet_test already exists.
set -eu

test_database=centralvet_test
project_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$project_root"

check_only=0
if [ "${1:-}" = "--check" ]; then
    check_only=1
elif [ $# -gt 0 ]; then
    echo "usage: $0 [--check]" >&2
    exit 1
fi

bootstrap_dir=${TEST_DB_BOOTSTRAP_DIR:-var/sql-bootstrap}
migrations_dir=src/app/database/migrations

# Same order as the development database, without the *.verify.sql files.
schema_files="
$bootstrap_dir/01-permission.mysql.sql
$bootstrap_dir/02-communication.mysql.sql
$bootstrap_dir/03-log.mysql.sql
$migrations_dir/20260919_add_missing_adianti_foreign_keys.sql
$migrations_dir/20260920_0001_foundation_multitenancy.sql
$migrations_dir/20260921_0002_phase1_clinic_core.sql
$migrations_dir/20260922_0003_phase2_encounter.sql
$migrations_dir/20260922_0004_phase3_prescription_exam_vaccine.sql
$migrations_dir/20260924_0005_phase4_procedure_stock_sale.sql
$migrations_dir/20260925_0006_phase5_financial.sql
$migrations_dir/20260930_0007_rodada2_cadastros_financeiro.sql
$migrations_dir/20260930_0008_queue_entry_appointment_unique.sql
$migrations_dir/20261001_0009_landing_lead.sql
$migrations_dir/20261005_0010_phase6a_hospitalization.sql
$migrations_dir/20261005_0011_phase6b_surgery.sql
"

# Preflight: no docker, no SQL. Paths contain no spaces.
preflight_failed=0
for file in $schema_files; do
    if [ ! -f "$file" ]; then
        case "$file" in
            "$bootstrap_dir"/*)
                echo "provision: missing $file; generate the Adianti base with scripts/prepare-adianti-bootstrap.sh" >&2 ;;
            *)
                echo "provision: missing $file" >&2 ;;
        esac
        preflight_failed=1
    elif grep -q '^---' "$file"; then
        echo "provision: $file starts a line with --- (SQLite-style heading, invalid in MySQL)" >&2
        preflight_failed=1
    fi
done

if [ "$preflight_failed" -ne 0 ]; then
    exit 1
fi

if [ "$check_only" -eq 1 ]; then
    echo "provision: check ok (no SQL executed)"
    exit 0
fi

# Reads KEY=value from .env without sourcing it (values are not shell code).
env_value() {
    value=$(grep -E "^$1=" .env 2>/dev/null | tail -n 1 | cut -d= -f2-) || value=''
    value=${value#\"}
    value=${value%\"}
    printf '%s' "$value"
}

if [ ! -f .env ]; then
    echo "provision: .env not found in $project_root" >&2
    exit 1
fi

migration_user=$(env_value MIGRATION_DB_USER)
migration_password=$(env_value MIGRATION_DB_PASSWORD)
runtime_user=$(env_value MYSQL_USER)
runtime_user=${runtime_user:-centralvet}

if [ -z "$migration_user" ] || [ -z "$migration_password" ]; then
    echo "provision: MIGRATION_DB_USER/MIGRATION_DB_PASSWORD missing in .env" >&2
    exit 1
fi

root_sql() {
    docker compose exec -T mysql sh -ceu 'MYSQL_PWD="$MYSQL_ROOT_PASSWORD" exec mysql -uroot --batch --skip-column-names'
}

exists=$(printf "SELECT COUNT(*) FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = '%s';\n" "$test_database" | root_sql)

if [ "$exists" != "0" ]; then
    echo "provision: refusing to run, database $test_database already exists" >&2
    exit 1
fi

# Step 1: database and grants (root, once).
echo "provision: step 1 - CREATE DATABASE $test_database and GRANTs"
root_sql <<SQL
CREATE DATABASE \`$test_database\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON \`$test_database\`.* TO '$migration_user'@'%';
GRANT ALL PRIVILEGES ON \`$test_database\`.* TO '$runtime_user'@'%';
SQL

# Step 2: schema, as checked by the preflight above.
for file in $schema_files; do
    echo "provision: step 2 - $file"
    docker compose exec -T -e MYSQL_PWD="$migration_password" mysql \
        mysql -u"$migration_user" --default-character-set=utf8mb4 "$test_database" < "$file"
done

echo "provision: done; now run scripts/test-db/verify.sql (SELECT only)"
