-- Central Vet Pro - Phase 7B documents (asynchronous PDF documents generated by the
-- worker for the vaccination card, prescription, medical certificate and surgical
-- consent, stored privately and versioned per source, and per-tenant templates of the
-- medical certificate)
-- Migration: 20261006_0013_phase7b_documents
-- Status: PREPARED ONLY. Do not execute without a fresh backup and explicit SQL approval.
-- Target: MySQL 8.0.x, database centralvet, after 20261006_0012_phase7a_communication
-- has been applied (tenant, system_unit, system_users, tutor, patient, stored_object
-- and schema_migrations already exist).
--
-- Effects:
--   * creates document_template (templates per tenant, with kind (medical_certificate
--     only for now), name, plain-text body with closed placeholders and status
--     active/inactive, plus the users who created and last updated it);
--   * creates generated_document (one requested PDF document: tenant, unit, patient,
--     tutor, kind vaccination_card/prescription/medical_certificate/surgery_consent,
--     source patient/prescription/surgery with its id, version per source (>= 1), the
--     optional template, title, the frozen body text of the certificate or consent, the
--     notify_tutor opt-in of the request, status queued/ready/failed with attempt count,
--     claim timestamp, stored object, storage key, size, SHA-256, last error code, the
--     ready/failed/notified timestamps and the requesting user);
--   * adds FKs from document_template to tenant/system_users (created_by, updated_by);
--     from generated_document to tenant/system_unit/patient/tutor/document_template/
--     stored_object/system_users (requested_by);
--   * creates 2 tables, 9 CHECK constraints (document_template.kind, .status;
--     generated_document.kind, .source, .status, .version, .notify, .ready, .failed),
--     3 UNIQUE constraints (document_template_tenant_name_uq,
--     generated_document_version_uq, generated_document_stored_object_uq) and
--     10 foreign keys.
--
-- No data is seeded by this migration: the 2 new tables start empty for every existing
-- tenant (without an active template the Application uses its built-in pt-BR default
-- text), and existing patient, vaccination, prescription, surgery, stored_object and
-- communication_message rows are preserved (no existing table is altered).
--
-- Risk: low; only new tables are created. Version allocation (MAX + 1 per source, retried
-- on a duplicate key), the conditional claim by claimed_at, the conditional markReady and
-- the deduplicated document_ready notice are Application rules. generated_document.body_text
-- stores the frozen certificate or consent text: it is personal data already held in the
-- clinic's records and must never be copied to logs, queue payloads, URLs or file names.
-- Retention and purge of PDFs and of body_text are not defined by this migration.
--
-- Rollback: restore the backup taken before applying, or write a numbered reverse
-- migration (see docs/runbooks/migration-rollback.md). Do not drop the new tables by hand
-- once documents have been generated: generated_document is the document history and
-- points to the stored PDF objects.
--
-- MySQL DDL commits implicitly. On failure, stop and inspect; do not rerun blindly.
-- The literal migration checksum below MUST be replaced with the approved artifact's
-- SHA-256 by the migration executor before this file is applied.

CREATE TABLE document_template (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    tenant_id bigint unsigned NOT NULL,
    kind varchar(30) NOT NULL,
    name varchar(120) NOT NULL,
    body_text text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_by_system_user_id int NOT NULL,
    updated_by_system_user_id int NULL,
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY document_template_tenant_name_uq (tenant_id, name),
    KEY document_template_kind_idx (tenant_id, kind, status),
    KEY document_template_created_by_idx (created_by_system_user_id),
    KEY document_template_updated_by_idx (updated_by_system_user_id),
    CONSTRAINT document_template_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenant (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT document_template_created_by_fk FOREIGN KEY (created_by_system_user_id) REFERENCES system_users (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT document_template_updated_by_fk FOREIGN KEY (updated_by_system_user_id) REFERENCES system_users (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT document_template_kind_ck CHECK (kind IN ('medical_certificate')),
    CONSTRAINT document_template_status_ck CHECK (status IN ('active', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE generated_document (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    tenant_id bigint unsigned NOT NULL,
    system_unit_id int NOT NULL,
    patient_id bigint unsigned NOT NULL,
    tutor_id bigint unsigned NOT NULL,
    kind varchar(30) NOT NULL,
    source_type varchar(30) NOT NULL,
    source_id bigint unsigned NOT NULL,
    version int unsigned NOT NULL,
    template_id bigint unsigned NULL,
    title varchar(190) NOT NULL,
    body_text mediumtext NULL,
    notify_tutor tinyint(1) NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'queued',
    attempt_count int unsigned NOT NULL DEFAULT 0,
    claimed_at timestamp(6) NULL DEFAULT NULL,
    stored_object_id bigint unsigned NULL,
    storage_key varchar(255) NULL,
    size_bytes bigint unsigned NULL,
    sha256 char(64) NULL,
    last_error_code varchar(60) NULL,
    ready_at timestamp(6) NULL DEFAULT NULL,
    failed_at timestamp(6) NULL DEFAULT NULL,
    notified_at timestamp(6) NULL DEFAULT NULL,
    requested_by_system_user_id int NOT NULL,
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY generated_document_version_uq (tenant_id, kind, source_type, source_id, version),
    UNIQUE KEY generated_document_stored_object_uq (stored_object_id),
    KEY generated_document_unit_status_idx (tenant_id, system_unit_id, status, created_at),
    KEY generated_document_patient_idx (tenant_id, patient_id, created_at),
    KEY generated_document_unit_idx (system_unit_id),
    KEY generated_document_patient_fk_idx (patient_id),
    KEY generated_document_tutor_idx (tutor_id),
    KEY generated_document_template_idx (template_id),
    KEY generated_document_requested_by_idx (requested_by_system_user_id),
    CONSTRAINT generated_document_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenant (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_unit_fk FOREIGN KEY (system_unit_id) REFERENCES system_unit (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_patient_fk FOREIGN KEY (patient_id) REFERENCES patient (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_tutor_fk FOREIGN KEY (tutor_id) REFERENCES tutor (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_template_fk FOREIGN KEY (template_id) REFERENCES document_template (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_stored_object_fk FOREIGN KEY (stored_object_id) REFERENCES stored_object (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_requested_by_fk FOREIGN KEY (requested_by_system_user_id) REFERENCES system_users (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT generated_document_kind_ck CHECK (kind IN ('vaccination_card', 'prescription', 'medical_certificate', 'surgery_consent')),
    CONSTRAINT generated_document_source_ck CHECK (source_type IN ('patient', 'prescription', 'surgery')),
    CONSTRAINT generated_document_status_ck CHECK (status IN ('queued', 'ready', 'failed')),
    CONSTRAINT generated_document_version_ck CHECK (version >= 1),
    CONSTRAINT generated_document_notify_ck CHECK (notify_tutor IN (0, 1)),
    CONSTRAINT generated_document_ready_ck CHECK ((status = 'ready' AND stored_object_id IS NOT NULL AND storage_key IS NOT NULL AND ready_at IS NOT NULL) OR (status <> 'ready' AND stored_object_id IS NULL AND ready_at IS NULL)),
    CONSTRAINT generated_document_failed_ck CHECK ((status = 'failed' AND failed_at IS NOT NULL AND last_error_code IS NOT NULL) OR (status <> 'failed' AND failed_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO schema_migrations (version, checksum)
VALUES ('20261006_0013_phase7b_documents',
        '0000000000000000000000000000000000000000000000000000000000000000' /* 64-char PLACEHOLDER: replace before applying */);
