<?php

declare(strict_types=1);

namespace CentralVet\Domain;

use CentralVet\Domain\Exception\InvalidStatusTransitionException;
use DateTimeImmutable;
use InvalidArgumentException;

/**
 * An internal prescription (medication, feeding or procedure) of a
 * hospitalization — domain aggregate for the `hospitalization_order` table
 * (migration 0010, Fase 6A).
 *
 * The period and frequency follow {@see AdministrationSchedule} (ends_at
 * mandatory, at most 30 days, 1..168 hours); the administrations themselves
 * are separate aggregates ({@see HospitalizationAdministration}) generated by
 * the application service. A product (stock item) is optional; when present,
 * `quantity_per_administration` (>= 1) is mandatory, matching
 * `hospitalization_order_product_ck`.
 *
 * ## Status state machine
 * `active` -> `suspended` via {@see self::suspend()} only. Mutable entity, like
 * {@see ExamRequest}. No Adianti dependency (ADR 0001).
 */
final class HospitalizationOrder
{
    public const TYPE_MEDICATION = 'medication';
    public const TYPE_FEEDING = 'feeding';
    public const TYPE_PROCEDURE = 'procedure';

    public const TYPES = [
        self::TYPE_MEDICATION,
        self::TYPE_FEEDING,
        self::TYPE_PROCEDURE,
    ];

    public const ROUTES = ['oral', 'iv', 'im', 'sc', 'topical', 'inhalation', 'other'];

    public const STATUS_ACTIVE = 'active';
    public const STATUS_SUSPENDED = 'suspended';

    private const VALID_STATUSES = [
        self::STATUS_ACTIVE,
        self::STATUS_SUSPENDED,
    ];

    private const DESCRIPTION_MAX_LENGTH = 255;
    private const DOSE_MAX_LENGTH = 120;

    private function __construct(
        private ?int $id,
        private readonly int $tenantId,
        private readonly int $hospitalizationId,
        private readonly string $orderType,
        private readonly string $descriptionText,
        private readonly ?int $productId,
        private readonly ?int $quantityPerAdministration,
        private readonly string $doseText,
        private readonly string $route,
        private readonly int $frequencyHours,
        private readonly DateTimeImmutable $startsAt,
        private readonly DateTimeImmutable $endsAt,
        private string $status,
        private readonly int $prescribedBySystemUserId,
        private ?DateTimeImmutable $suspendedAt,
    ) {
    }

    /**
     * Creates a new, `active` order.
     *
     * @throws InvalidArgumentException on any invalid field (see
     *         {@see AdministrationSchedule::assertValid()} for the period).
     */
    public static function prescribe(
        int $tenantId,
        int $hospitalizationId,
        string $orderType,
        string $descriptionText,
        ?int $productId,
        ?int $quantityPerAdministration,
        string $doseText,
        string $route,
        int $frequencyHours,
        DateTimeImmutable $startsAt,
        DateTimeImmutable $endsAt,
        int $prescribedBySystemUserId,
    ): self {
        if ($tenantId <= 0) {
            throw new InvalidArgumentException('Tenant id must be positive');
        }

        if ($hospitalizationId <= 0) {
            throw new InvalidArgumentException('hospitalization_id must be positive');
        }

        if (!in_array($orderType, self::TYPES, true)) {
            throw new InvalidArgumentException("Unknown order_type \"{$orderType}\"");
        }

        $descriptionText = trim($descriptionText);
        if ($descriptionText === '') {
            throw new InvalidArgumentException('description_text is required');
        }

        if (mb_strlen($descriptionText) > self::DESCRIPTION_MAX_LENGTH) {
            throw new InvalidArgumentException('description_text must have at most 255 characters');
        }

        if ($productId !== null) {
            if ($productId <= 0) {
                throw new InvalidArgumentException('product_id must be positive');
            }

            if ($quantityPerAdministration === null || $quantityPerAdministration < 1) {
                throw new InvalidArgumentException('quantity_per_administration is required when a product is selected');
            }
        } elseif ($quantityPerAdministration !== null) {
            throw new InvalidArgumentException('quantity_per_administration requires a product');
        }

        $doseText = trim($doseText);
        if (mb_strlen($doseText) > self::DOSE_MAX_LENGTH) {
            throw new InvalidArgumentException('dose_text must have at most 120 characters');
        }

        if (!in_array($route, self::ROUTES, true)) {
            throw new InvalidArgumentException("Unknown route \"{$route}\"");
        }

        AdministrationSchedule::assertValid($startsAt, $endsAt, $frequencyHours);

        if ($prescribedBySystemUserId <= 0) {
            throw new InvalidArgumentException('prescribed_by_system_user_id must be positive');
        }

        return new self(
            id: null,
            tenantId: $tenantId,
            hospitalizationId: $hospitalizationId,
            orderType: $orderType,
            descriptionText: $descriptionText,
            productId: $productId,
            quantityPerAdministration: $quantityPerAdministration,
            doseText: $doseText,
            route: $route,
            frequencyHours: $frequencyHours,
            startsAt: $startsAt,
            endsAt: $endsAt,
            status: self::STATUS_ACTIVE,
            prescribedBySystemUserId: $prescribedBySystemUserId,
            suspendedAt: null,
        );
    }

    /**
     * Rebuilds a persisted order. Repositories use this to hydrate rows;
     * application code should use prescribe() instead.
     */
    public static function reconstitute(
        int $id,
        int $tenantId,
        int $hospitalizationId,
        string $orderType,
        string $descriptionText,
        ?int $productId,
        ?int $quantityPerAdministration,
        string $doseText,
        string $route,
        int $frequencyHours,
        DateTimeImmutable $startsAt,
        DateTimeImmutable $endsAt,
        string $status,
        int $prescribedBySystemUserId,
        ?DateTimeImmutable $suspendedAt,
    ): self {
        if (!in_array($status, self::VALID_STATUSES, true)) {
            throw new InvalidArgumentException("Unknown hospitalization_order status \"{$status}\"");
        }

        return new self(
            $id,
            $tenantId,
            $hospitalizationId,
            $orderType,
            $descriptionText,
            $productId,
            $quantityPerAdministration,
            $doseText,
            $route,
            $frequencyHours,
            $startsAt,
            $endsAt,
            $status,
            $prescribedBySystemUserId,
            $suspendedAt,
        );
    }

    /** Assigns the identifier generated on first persistence. */
    public function assignId(int $id): void
    {
        if ($this->id !== null) {
            throw new InvalidArgumentException('HospitalizationOrder already has an id');
        }

        if ($id <= 0) {
            throw new InvalidArgumentException('Id must be positive');
        }

        $this->id = $id;
    }

    /**
     * Suspends an active order. Cancelling its pending administrations is
     * the application service's job.
     *
     * @throws InvalidStatusTransitionException when the order is not active.
     */
    public function suspend(DateTimeImmutable $at): void
    {
        if ($this->status !== self::STATUS_ACTIVE) {
            throw new InvalidStatusTransitionException(
                sprintf('Order %s is not active', $this->id !== null ? (string) $this->id : '(new)')
            );
        }

        $this->status = self::STATUS_SUSPENDED;
        $this->suspendedAt = $at;
    }

    public function id(): ?int
    {
        return $this->id;
    }

    public function tenantId(): int
    {
        return $this->tenantId;
    }

    public function hospitalizationId(): int
    {
        return $this->hospitalizationId;
    }

    public function orderType(): string
    {
        return $this->orderType;
    }

    public function descriptionText(): string
    {
        return $this->descriptionText;
    }

    public function productId(): ?int
    {
        return $this->productId;
    }

    public function quantityPerAdministration(): ?int
    {
        return $this->quantityPerAdministration;
    }

    public function doseText(): string
    {
        return $this->doseText;
    }

    public function route(): string
    {
        return $this->route;
    }

    public function frequencyHours(): int
    {
        return $this->frequencyHours;
    }

    public function startsAt(): DateTimeImmutable
    {
        return $this->startsAt;
    }

    public function endsAt(): DateTimeImmutable
    {
        return $this->endsAt;
    }

    public function status(): string
    {
        return $this->status;
    }

    public function prescribedBySystemUserId(): int
    {
        return $this->prescribedBySystemUserId;
    }

    public function suspendedAt(): ?DateTimeImmutable
    {
        return $this->suspendedAt;
    }
}
